/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GroupService } from "../group.service";
import { GroupCreateInput } from "./GroupCreateInput";
import { Group } from "./Group";
import { GroupFindManyArgs } from "./GroupFindManyArgs";
import { GroupWhereUniqueInput } from "./GroupWhereUniqueInput";
import { GroupUpdateInput } from "./GroupUpdateInput";
import { LessonAssignmentFindManyArgs } from "../../lessonAssignment/base/LessonAssignmentFindManyArgs";
import { LessonAssignment } from "../../lessonAssignment/base/LessonAssignment";
import { LessonAssignmentWhereUniqueInput } from "../../lessonAssignment/base/LessonAssignmentWhereUniqueInput";

export class GroupControllerBase {
  constructor(protected readonly service: GroupService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Group })
  async createGroup(@common.Body() data: GroupCreateInput): Promise<Group> {
    return await this.service.createGroup({
      data: data,
      select: {
        code: true,
        createdAt: true,
        faculty: true,
        id: true,
        name: true,
        preferredSlots: true,
        specialization: true,
        studentCount: true,
        studyYear: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Group] })
  @ApiNestedQuery(GroupFindManyArgs)
  async groups(@common.Req() request: Request): Promise<Group[]> {
    const args = plainToClass(GroupFindManyArgs, request.query);
    return this.service.groups({
      ...args,
      select: {
        code: true,
        createdAt: true,
        faculty: true,
        id: true,
        name: true,
        preferredSlots: true,
        specialization: true,
        studentCount: true,
        studyYear: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Group })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async group(
    @common.Param() params: GroupWhereUniqueInput
  ): Promise<Group | null> {
    const result = await this.service.group({
      where: params,
      select: {
        code: true,
        createdAt: true,
        faculty: true,
        id: true,
        name: true,
        preferredSlots: true,
        specialization: true,
        studentCount: true,
        studyYear: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Group })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGroup(
    @common.Param() params: GroupWhereUniqueInput,
    @common.Body() data: GroupUpdateInput
  ): Promise<Group | null> {
    try {
      return await this.service.updateGroup({
        where: params,
        data: data,
        select: {
          code: true,
          createdAt: true,
          faculty: true,
          id: true,
          name: true,
          preferredSlots: true,
          specialization: true,
          studentCount: true,
          studyYear: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Group })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGroup(
    @common.Param() params: GroupWhereUniqueInput
  ): Promise<Group | null> {
    try {
      return await this.service.deleteGroup({
        where: params,
        select: {
          code: true,
          createdAt: true,
          faculty: true,
          id: true,
          name: true,
          preferredSlots: true,
          specialization: true,
          studentCount: true,
          studyYear: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/lessonAssignments")
  @ApiNestedQuery(LessonAssignmentFindManyArgs)
  async findLessonAssignments(
    @common.Req() request: Request,
    @common.Param() params: GroupWhereUniqueInput
  ): Promise<LessonAssignment[]> {
    const query = plainToClass(LessonAssignmentFindManyArgs, request.query);
    const results = await this.service.findLessonAssignments(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationSlots: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        room: {
          select: {
            id: true,
          },
        },

        slot: {
          select: {
            id: true,
          },
        },

        teacher: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/lessonAssignments")
  async connectLessonAssignments(
    @common.Param() params: GroupWhereUniqueInput,
    @common.Body() body: LessonAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessonAssignments: {
        connect: body,
      },
    };
    await this.service.updateGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/lessonAssignments")
  async updateLessonAssignments(
    @common.Param() params: GroupWhereUniqueInput,
    @common.Body() body: LessonAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessonAssignments: {
        set: body,
      },
    };
    await this.service.updateGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/lessonAssignments")
  async disconnectLessonAssignments(
    @common.Param() params: GroupWhereUniqueInput,
    @common.Body() body: LessonAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessonAssignments: {
        disconnect: body,
      },
    };
    await this.service.updateGroup({
      where: params,
      data,
      select: { id: true },
    });
  }
}
