/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ScheduleVersionService } from "../scheduleVersion.service";
import { ScheduleVersionCreateInput } from "./ScheduleVersionCreateInput";
import { ScheduleVersion } from "./ScheduleVersion";
import { ScheduleVersionFindManyArgs } from "./ScheduleVersionFindManyArgs";
import { ScheduleVersionWhereUniqueInput } from "./ScheduleVersionWhereUniqueInput";
import { ScheduleVersionUpdateInput } from "./ScheduleVersionUpdateInput";

export class ScheduleVersionControllerBase {
  constructor(protected readonly service: ScheduleVersionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ScheduleVersion })
  async createScheduleVersion(
    @common.Body() data: ScheduleVersionCreateInput
  ): Promise<ScheduleVersion> {
    return await this.service.createScheduleVersion({
      data: data,
      select: {
        createdAt: true,
        generatedBy: true,
        id: true,
        scoreMetrics: true,
        serializedSchedule: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ScheduleVersion] })
  @ApiNestedQuery(ScheduleVersionFindManyArgs)
  async scheduleVersions(
    @common.Req() request: Request
  ): Promise<ScheduleVersion[]> {
    const args = plainToClass(ScheduleVersionFindManyArgs, request.query);
    return this.service.scheduleVersions({
      ...args,
      select: {
        createdAt: true,
        generatedBy: true,
        id: true,
        scoreMetrics: true,
        serializedSchedule: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ScheduleVersion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async scheduleVersion(
    @common.Param() params: ScheduleVersionWhereUniqueInput
  ): Promise<ScheduleVersion | null> {
    const result = await this.service.scheduleVersion({
      where: params,
      select: {
        createdAt: true,
        generatedBy: true,
        id: true,
        scoreMetrics: true,
        serializedSchedule: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ScheduleVersion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateScheduleVersion(
    @common.Param() params: ScheduleVersionWhereUniqueInput,
    @common.Body() data: ScheduleVersionUpdateInput
  ): Promise<ScheduleVersion | null> {
    try {
      return await this.service.updateScheduleVersion({
        where: params,
        data: data,
        select: {
          createdAt: true,
          generatedBy: true,
          id: true,
          scoreMetrics: true,
          serializedSchedule: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ScheduleVersion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteScheduleVersion(
    @common.Param() params: ScheduleVersionWhereUniqueInput
  ): Promise<ScheduleVersion | null> {
    try {
      return await this.service.deleteScheduleVersion({
        where: params,
        select: {
          createdAt: true,
          generatedBy: true,
          id: true,
          scoreMetrics: true,
          serializedSchedule: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
