/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ScheduleVersion } from "./ScheduleVersion";
import { ScheduleVersionCountArgs } from "./ScheduleVersionCountArgs";
import { ScheduleVersionFindManyArgs } from "./ScheduleVersionFindManyArgs";
import { ScheduleVersionFindUniqueArgs } from "./ScheduleVersionFindUniqueArgs";
import { CreateScheduleVersionArgs } from "./CreateScheduleVersionArgs";
import { UpdateScheduleVersionArgs } from "./UpdateScheduleVersionArgs";
import { DeleteScheduleVersionArgs } from "./DeleteScheduleVersionArgs";
import { ScheduleVersionService } from "../scheduleVersion.service";
@graphql.Resolver(() => ScheduleVersion)
export class ScheduleVersionResolverBase {
  constructor(protected readonly service: ScheduleVersionService) {}

  async _scheduleVersionsMeta(
    @graphql.Args() args: ScheduleVersionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ScheduleVersion])
  async scheduleVersions(
    @graphql.Args() args: ScheduleVersionFindManyArgs
  ): Promise<ScheduleVersion[]> {
    return this.service.scheduleVersions(args);
  }

  @graphql.Query(() => ScheduleVersion, { nullable: true })
  async scheduleVersion(
    @graphql.Args() args: ScheduleVersionFindUniqueArgs
  ): Promise<ScheduleVersion | null> {
    const result = await this.service.scheduleVersion(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ScheduleVersion)
  async createScheduleVersion(
    @graphql.Args() args: CreateScheduleVersionArgs
  ): Promise<ScheduleVersion> {
    return await this.service.createScheduleVersion({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ScheduleVersion)
  async updateScheduleVersion(
    @graphql.Args() args: UpdateScheduleVersionArgs
  ): Promise<ScheduleVersion | null> {
    try {
      return await this.service.updateScheduleVersion({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ScheduleVersion)
  async deleteScheduleVersion(
    @graphql.Args() args: DeleteScheduleVersionArgs
  ): Promise<ScheduleVersion | null> {
    try {
      return await this.service.deleteScheduleVersion(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
