/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ScheduleVersion as PrismaScheduleVersion,
} from "@prisma/client";

export class ScheduleVersionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ScheduleVersionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.scheduleVersion.count(args);
  }

  async scheduleVersions(
    args: Prisma.ScheduleVersionFindManyArgs
  ): Promise<PrismaScheduleVersion[]> {
    return this.prisma.scheduleVersion.findMany(args);
  }
  async scheduleVersion(
    args: Prisma.ScheduleVersionFindUniqueArgs
  ): Promise<PrismaScheduleVersion | null> {
    return this.prisma.scheduleVersion.findUnique(args);
  }
  async createScheduleVersion(
    args: Prisma.ScheduleVersionCreateArgs
  ): Promise<PrismaScheduleVersion> {
    return this.prisma.scheduleVersion.create(args);
  }
  async updateScheduleVersion(
    args: Prisma.ScheduleVersionUpdateArgs
  ): Promise<PrismaScheduleVersion> {
    return this.prisma.scheduleVersion.update(args);
  }
  async deleteScheduleVersion(
    args: Prisma.ScheduleVersionDeleteArgs
  ): Promise<PrismaScheduleVersion> {
    return this.prisma.scheduleVersion.delete(args);
  }
}
