/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  LessonAssignment as PrismaLessonAssignment,
  Course as PrismaCourse,
  Group as PrismaGroup,
  Room as PrismaRoom,
  Slot as PrismaSlot,
  Teacher as PrismaTeacher,
} from "@prisma/client";

export class LessonAssignmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LessonAssignmentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.lessonAssignment.count(args);
  }

  async lessonAssignments(
    args: Prisma.LessonAssignmentFindManyArgs
  ): Promise<PrismaLessonAssignment[]> {
    return this.prisma.lessonAssignment.findMany(args);
  }
  async lessonAssignment(
    args: Prisma.LessonAssignmentFindUniqueArgs
  ): Promise<PrismaLessonAssignment | null> {
    return this.prisma.lessonAssignment.findUnique(args);
  }
  async createLessonAssignment(
    args: Prisma.LessonAssignmentCreateArgs
  ): Promise<PrismaLessonAssignment> {
    return this.prisma.lessonAssignment.create(args);
  }
  async updateLessonAssignment(
    args: Prisma.LessonAssignmentUpdateArgs
  ): Promise<PrismaLessonAssignment> {
    return this.prisma.lessonAssignment.update(args);
  }
  async deleteLessonAssignment(
    args: Prisma.LessonAssignmentDeleteArgs
  ): Promise<PrismaLessonAssignment> {
    return this.prisma.lessonAssignment.delete(args);
  }

  async getCourse(parentId: string): Promise<PrismaCourse | null> {
    return this.prisma.lessonAssignment
      .findUnique({
        where: { id: parentId },
      })
      .course();
  }

  async getGroup(parentId: string): Promise<PrismaGroup | null> {
    return this.prisma.lessonAssignment
      .findUnique({
        where: { id: parentId },
      })
      .group();
  }

  async getRoom(parentId: string): Promise<PrismaRoom | null> {
    return this.prisma.lessonAssignment
      .findUnique({
        where: { id: parentId },
      })
      .room();
  }

  async getSlot(parentId: string): Promise<PrismaSlot | null> {
    return this.prisma.lessonAssignment
      .findUnique({
        where: { id: parentId },
      })
      .slot();
  }

  async getTeacher(parentId: string): Promise<PrismaTeacher | null> {
    return this.prisma.lessonAssignment
      .findUnique({
        where: { id: parentId },
      })
      .teacher();
  }
}
