/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { LessonAssignmentWhereInput } from "./LessonAssignmentWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class LessonAssignmentListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => LessonAssignmentWhereInput,
  })
  @ValidateNested()
  @Type(() => LessonAssignmentWhereInput)
  @IsOptional()
  @Field(() => LessonAssignmentWhereInput, {
    nullable: true,
  })
  every?: LessonAssignmentWhereInput;

  @ApiProperty({
    required: false,
    type: () => LessonAssignmentWhereInput,
  })
  @ValidateNested()
  @Type(() => LessonAssignmentWhereInput)
  @IsOptional()
  @Field(() => LessonAssignmentWhereInput, {
    nullable: true,
  })
  some?: LessonAssignmentWhereInput;

  @ApiProperty({
    required: false,
    type: () => LessonAssignmentWhereInput,
  })
  @ValidateNested()
  @Type(() => LessonAssignmentWhereInput)
  @IsOptional()
  @Field(() => LessonAssignmentWhereInput, {
    nullable: true,
  })
  none?: LessonAssignmentWhereInput;
}
export { LessonAssignmentListRelationFilter as LessonAssignmentListRelationFilter };
