/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LessonAssignmentService } from "../lessonAssignment.service";
import { LessonAssignmentCreateInput } from "./LessonAssignmentCreateInput";
import { LessonAssignment } from "./LessonAssignment";
import { LessonAssignmentFindManyArgs } from "./LessonAssignmentFindManyArgs";
import { LessonAssignmentWhereUniqueInput } from "./LessonAssignmentWhereUniqueInput";
import { LessonAssignmentUpdateInput } from "./LessonAssignmentUpdateInput";

export class LessonAssignmentControllerBase {
  constructor(protected readonly service: LessonAssignmentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LessonAssignment })
  async createLessonAssignment(
    @common.Body() data: LessonAssignmentCreateInput
  ): Promise<LessonAssignment> {
    return await this.service.createLessonAssignment({
      data: {
        ...data,

        course: data.course
          ? {
              connect: data.course,
            }
          : undefined,

        group: data.group
          ? {
              connect: data.group,
            }
          : undefined,

        room: data.room
          ? {
              connect: data.room,
            }
          : undefined,

        slot: data.slot
          ? {
              connect: data.slot,
            }
          : undefined,

        teacher: data.teacher
          ? {
              connect: data.teacher,
            }
          : undefined,
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationSlots: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        room: {
          select: {
            id: true,
          },
        },

        slot: {
          select: {
            id: true,
          },
        },

        teacher: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [LessonAssignment] })
  @ApiNestedQuery(LessonAssignmentFindManyArgs)
  async lessonAssignments(
    @common.Req() request: Request
  ): Promise<LessonAssignment[]> {
    const args = plainToClass(LessonAssignmentFindManyArgs, request.query);
    return this.service.lessonAssignments({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationSlots: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        room: {
          select: {
            id: true,
          },
        },

        slot: {
          select: {
            id: true,
          },
        },

        teacher: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LessonAssignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async lessonAssignment(
    @common.Param() params: LessonAssignmentWhereUniqueInput
  ): Promise<LessonAssignment | null> {
    const result = await this.service.lessonAssignment({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationSlots: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        room: {
          select: {
            id: true,
          },
        },

        slot: {
          select: {
            id: true,
          },
        },

        teacher: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LessonAssignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLessonAssignment(
    @common.Param() params: LessonAssignmentWhereUniqueInput,
    @common.Body() data: LessonAssignmentUpdateInput
  ): Promise<LessonAssignment | null> {
    try {
      return await this.service.updateLessonAssignment({
        where: params,
        data: {
          ...data,

          course: data.course
            ? {
                connect: data.course,
              }
            : undefined,

          group: data.group
            ? {
                connect: data.group,
              }
            : undefined,

          room: data.room
            ? {
                connect: data.room,
              }
            : undefined,

          slot: data.slot
            ? {
                connect: data.slot,
              }
            : undefined,

          teacher: data.teacher
            ? {
                connect: data.teacher,
              }
            : undefined,
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          durationSlots: true,

          group: {
            select: {
              id: true,
            },
          },

          id: true,

          room: {
            select: {
              id: true,
            },
          },

          slot: {
            select: {
              id: true,
            },
          },

          teacher: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LessonAssignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLessonAssignment(
    @common.Param() params: LessonAssignmentWhereUniqueInput
  ): Promise<LessonAssignment | null> {
    try {
      return await this.service.deleteLessonAssignment({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          durationSlots: true,

          group: {
            select: {
              id: true,
            },
          },

          id: true,

          room: {
            select: {
              id: true,
            },
          },

          slot: {
            select: {
              id: true,
            },
          },

          teacher: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
