/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LessonAssignment } from "./LessonAssignment";
import { LessonAssignmentCountArgs } from "./LessonAssignmentCountArgs";
import { LessonAssignmentFindManyArgs } from "./LessonAssignmentFindManyArgs";
import { LessonAssignmentFindUniqueArgs } from "./LessonAssignmentFindUniqueArgs";
import { CreateLessonAssignmentArgs } from "./CreateLessonAssignmentArgs";
import { UpdateLessonAssignmentArgs } from "./UpdateLessonAssignmentArgs";
import { DeleteLessonAssignmentArgs } from "./DeleteLessonAssignmentArgs";
import { Course } from "../../course/base/Course";
import { Group } from "../../group/base/Group";
import { Room } from "../../room/base/Room";
import { Slot } from "../../slot/base/Slot";
import { Teacher } from "../../teacher/base/Teacher";
import { LessonAssignmentService } from "../lessonAssignment.service";
@graphql.Resolver(() => LessonAssignment)
export class LessonAssignmentResolverBase {
  constructor(protected readonly service: LessonAssignmentService) {}

  async _lessonAssignmentsMeta(
    @graphql.Args() args: LessonAssignmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LessonAssignment])
  async lessonAssignments(
    @graphql.Args() args: LessonAssignmentFindManyArgs
  ): Promise<LessonAssignment[]> {
    return this.service.lessonAssignments(args);
  }

  @graphql.Query(() => LessonAssignment, { nullable: true })
  async lessonAssignment(
    @graphql.Args() args: LessonAssignmentFindUniqueArgs
  ): Promise<LessonAssignment | null> {
    const result = await this.service.lessonAssignment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LessonAssignment)
  async createLessonAssignment(
    @graphql.Args() args: CreateLessonAssignmentArgs
  ): Promise<LessonAssignment> {
    return await this.service.createLessonAssignment({
      ...args,
      data: {
        ...args.data,

        course: args.data.course
          ? {
              connect: args.data.course,
            }
          : undefined,

        group: args.data.group
          ? {
              connect: args.data.group,
            }
          : undefined,

        room: args.data.room
          ? {
              connect: args.data.room,
            }
          : undefined,

        slot: args.data.slot
          ? {
              connect: args.data.slot,
            }
          : undefined,

        teacher: args.data.teacher
          ? {
              connect: args.data.teacher,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => LessonAssignment)
  async updateLessonAssignment(
    @graphql.Args() args: UpdateLessonAssignmentArgs
  ): Promise<LessonAssignment | null> {
    try {
      return await this.service.updateLessonAssignment({
        ...args,
        data: {
          ...args.data,

          course: args.data.course
            ? {
                connect: args.data.course,
              }
            : undefined,

          group: args.data.group
            ? {
                connect: args.data.group,
              }
            : undefined,

          room: args.data.room
            ? {
                connect: args.data.room,
              }
            : undefined,

          slot: args.data.slot
            ? {
                connect: args.data.slot,
              }
            : undefined,

          teacher: args.data.teacher
            ? {
                connect: args.data.teacher,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LessonAssignment)
  async deleteLessonAssignment(
    @graphql.Args() args: DeleteLessonAssignmentArgs
  ): Promise<LessonAssignment | null> {
    try {
      return await this.service.deleteLessonAssignment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  async getCourse(
    @graphql.Parent() parent: LessonAssignment
  ): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Group, {
    nullable: true,
    name: "group",
  })
  async getGroup(
    @graphql.Parent() parent: LessonAssignment
  ): Promise<Group | null> {
    const result = await this.service.getGroup(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Room, {
    nullable: true,
    name: "room",
  })
  async getRoom(
    @graphql.Parent() parent: LessonAssignment
  ): Promise<Room | null> {
    const result = await this.service.getRoom(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Slot, {
    nullable: true,
    name: "slot",
  })
  async getSlot(
    @graphql.Parent() parent: LessonAssignment
  ): Promise<Slot | null> {
    const result = await this.service.getSlot(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Teacher, {
    nullable: true,
    name: "teacher",
  })
  async getTeacher(
    @graphql.Parent() parent: LessonAssignment
  ): Promise<Teacher | null> {
    const result = await this.service.getTeacher(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
