/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SlotService } from "../slot.service";
import { SlotCreateInput } from "./SlotCreateInput";
import { Slot } from "./Slot";
import { SlotFindManyArgs } from "./SlotFindManyArgs";
import { SlotWhereUniqueInput } from "./SlotWhereUniqueInput";
import { SlotUpdateInput } from "./SlotUpdateInput";
import { LessonAssignmentFindManyArgs } from "../../lessonAssignment/base/LessonAssignmentFindManyArgs";
import { LessonAssignment } from "../../lessonAssignment/base/LessonAssignment";
import { LessonAssignmentWhereUniqueInput } from "../../lessonAssignment/base/LessonAssignmentWhereUniqueInput";

export class SlotControllerBase {
  constructor(protected readonly service: SlotService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Slot })
  async createSlot(@common.Body() data: SlotCreateInput): Promise<Slot> {
    return await this.service.createSlot({
      data: data,
      select: {
        createdAt: true,
        dayOfWeek: true,
        endTime: true,
        id: true,
        slotIndex: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Slot] })
  @ApiNestedQuery(SlotFindManyArgs)
  async slots(@common.Req() request: Request): Promise<Slot[]> {
    const args = plainToClass(SlotFindManyArgs, request.query);
    return this.service.slots({
      ...args,
      select: {
        createdAt: true,
        dayOfWeek: true,
        endTime: true,
        id: true,
        slotIndex: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async slot(
    @common.Param() params: SlotWhereUniqueInput
  ): Promise<Slot | null> {
    const result = await this.service.slot({
      where: params,
      select: {
        createdAt: true,
        dayOfWeek: true,
        endTime: true,
        id: true,
        slotIndex: true,
        startTime: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSlot(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() data: SlotUpdateInput
  ): Promise<Slot | null> {
    try {
      return await this.service.updateSlot({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dayOfWeek: true,
          endTime: true,
          id: true,
          slotIndex: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSlot(
    @common.Param() params: SlotWhereUniqueInput
  ): Promise<Slot | null> {
    try {
      return await this.service.deleteSlot({
        where: params,
        select: {
          createdAt: true,
          dayOfWeek: true,
          endTime: true,
          id: true,
          slotIndex: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/lessonAssignments")
  @ApiNestedQuery(LessonAssignmentFindManyArgs)
  async findLessonAssignments(
    @common.Req() request: Request,
    @common.Param() params: SlotWhereUniqueInput
  ): Promise<LessonAssignment[]> {
    const query = plainToClass(LessonAssignmentFindManyArgs, request.query);
    const results = await this.service.findLessonAssignments(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        durationSlots: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        room: {
          select: {
            id: true,
          },
        },

        slot: {
          select: {
            id: true,
          },
        },

        teacher: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/lessonAssignments")
  async connectLessonAssignments(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() body: LessonAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessonAssignments: {
        connect: body,
      },
    };
    await this.service.updateSlot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/lessonAssignments")
  async updateLessonAssignments(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() body: LessonAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessonAssignments: {
        set: body,
      },
    };
    await this.service.updateSlot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/lessonAssignments")
  async disconnectLessonAssignments(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() body: LessonAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessonAssignments: {
        disconnect: body,
      },
    };
    await this.service.updateSlot({
      where: params,
      data,
      select: { id: true },
    });
  }
}
